"""
Using python random module to generate random numbers and testing their randomness and uniformity
"""

import numpy as np
import matplotlib.pyplot as plt


def main():
    random_numbers = np.random.rand(100)
    i_values = np.arange(0, 100)
    fig, ax = plt.subplots()
    ax.plot(i_values, random_numbers)
    ax.set(xlabel='Sequence Number', ylabel='Random Number', title='Plot of uniform pseudorandom numbers generated by '
                                                                   'python numpy random module')
    ax.grid()
    fig.savefig('test_random.png')
    plt.show()


if __name__ == '__main__':
    main()
